name: sequelize-test
services:
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    volumes:
      - ./src:/app/src:ro

  db:
    image: postgres:latest
    container_name: pg-db
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
      - POSTGRES_DB=testdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U username -d testdb']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
